// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weffofqnfyzzixyfqjij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZmZvZnFuZnl6eml4eWZxamlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTQ3MDUsImV4cCI6MjA2NDU3MDcwNX0.C_z7gGtbgPhhavuAF8fuumMv6wV8nuODe67BWOgQIrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);